name: Publish APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: "./gradlew assembleDebug"
      - name: Upload the APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug
          if-no-files-found: error